In [969]:
import numpy as np

In [970]:
np.set_printoptions(suppress = True, linewidth = 100, precision = 2)

In [971]:
fname = "F:/skillss/data analyst course/data processing via python udemy course/S28 - A Loan Data Example with NumPy/loan-data.csv"

In [972]:
#load the whole dataset to observe
data = np.genfromtxt(fname,
                     delimiter= ';',
                     skip_header=0,
                     autostrip=True,
                    dtype = str)
data.shape,  type(data),  data

((10001, 14),
 numpy.ndarray,
 array([['id', 'issue_d', 'loan_amnt', ..., 'url', 'addr_state', 'total_pymnt'],
        ['48010226', 'May-15', '35000.0', ...,
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA', '9452.96'],
        ['57693261', '', '30000.0', ...,
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY', '4679.7'],
        ...,
        ['50415990', 'Jun-15', '10000.0', ...,
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA', '2185.64'],
        ['46154151', 'Apr-15', '', ...,
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH', '3199.4'],
        ['66055249', 'Dec-15', '10000.0', ...,
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL', '301.9']],
       dtype='<U69'))

In [973]:
#reload the whole dataset to observe
data = np.genfromtxt(fname,
                     delimiter= ';',
                     skip_header=1,
                     autostrip=True)
data.shape,type(data),data

((10000, 14),
 numpy.ndarray,
 array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
        [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
        [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
        ...,
        [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
        [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
        [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]]))

In [974]:
#checking the amount missing values in each column
for i in range(0,14):
    if np.isnan(data[:,i]).sum() != 0:
        print(str(np.isnan(data[:,i]).sum()) + ' mv in column ' + str(i))
    else:
         print(str(0) + ' mv in column ' + str(i))

0 mv in column 0
10000 mv in column 1
500 mv in column 2
10000 mv in column 3
500 mv in column 4
10000 mv in column 5
6004 mv in column 6
501 mv in column 7
10000 mv in column 8
10000 mv in column 9
10000 mv in column 10
10000 mv in column 11
10000 mv in column 12
500 mv in column 13


In [975]:
#generate some values for the missing values of the dataset
temporary_fill = np.nanmax(data)+1
temporary_stats = np.array([np.nanmean(data,axis = 0),
                            np.nanmin(data,axis = 0),
                            np.nanmax(data,axis = 0)])
temporary_fill,temporary_stats,temporary_stats.shape

C:\Users\Mohammed Riad\AppData\Local\Temp\ipykernel_7208\2465909168.py:3: RuntimeWarning: Mean of empty slice
  temporary_stats = np.array([np.nanmean(data,axis = 0),
C:\Users\Mohammed Riad\AppData\Local\Temp\ipykernel_7208\2465909168.py:4: RuntimeWarning: All-NaN slice encountered
  np.nanmin(data,axis = 0),
C:\Users\Mohammed Riad\AppData\Local\Temp\ipykernel_7208\2465909168.py:5: RuntimeWarning: All-NaN slice encountered
  np.nanmax(data,axis = 0)])


(np.float64(68616520.0),
 array([[54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
              440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
        [  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
               31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
        [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
             1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]]),
 (3, 14))

# Spiliting the data set into numeric and strings

In [976]:
column_strings= np.argwhere(np.isnan(temporary_stats[0])).squeeze()
column_numeric = np.argwhere((np.isnan(temporary_stats[0])==False)).squeeze()

In [977]:
#this column contains string data
column_strings,column_strings.shape[0]

(array([ 1,  3,  5,  8,  9, 10, 11, 12]), 8)

In [978]:
#this columns contains numeric data
column_numeric,column_numeric.shape[0]

(array([ 0,  2,  4,  6,  7, 13]), 6)

In [979]:
loan_data_strings = np.genfromtxt(fname,
                                  delimiter=';',
                                  dtype = str,
                                  skip_header=1,
                                  usecols=column_strings,
                                  autostrip=True)

loan_data_numeric = np.genfromtxt(fname,
                                  delimiter = ';',
                                  skip_header= 1,
                                  usecols= column_numeric,
                                 filling_values=temporary_fill)
                                    

In [980]:
loan_data_strings.shape,loan_data_strings

((10000, 8),
 array([['May-15', 'Current', '36 months', ..., 'Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
        ['', 'Current', '36 months', ..., 'Source Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
        ['Sep-15', 'Current', '36 months', ..., 'Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
        ...,
        ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
        ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
        ['Dec-15', 'Current', '36 months', ..., '',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
       dtype='<U69'))

In [981]:
loan_data_numeric.shape,  np.isnan(loan_data_numeric).sum(), loan_data_numeric

((10000, 6),
 np.int64(0),
 array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
        [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
        [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
        ...,
        [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
        [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
        [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]]))

In [982]:
column_header = np.genfromtxt(fname,
                              delimiter=';',
                              dtype = str,
                              skip_footer=data.shape[0],
                              autostrip=True)
column_header.shape,column_header

((14,),
 array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
        'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
        'total_pymnt'], dtype='<U19'))

In [983]:
header_strings = column_header[column_strings]
header_numeric = column_header[column_numeric]

In [984]:
header_strings , header_numeric

(array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
        'addr_state'], dtype='<U19'),
 array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19'))

### spiliting the whole dataset into strings and numeric has been completed.
Creating Checkpoints

In [985]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header = checkpoint_header, data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

In [986]:
checkpoint_test = checkpoint('checkpoint-test',header_strings,loan_data_strings)
checkpoint_test['header'],checkpoint_test['data']

(array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
        'addr_state'], dtype='<U19'),
 array([['May-15', 'Current', '36 months', ..., 'Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
        ['', 'Current', '36 months', ..., 'Source Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
        ['Sep-15', 'Current', '36 months', ..., 'Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
        ...,
        ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
        ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
         'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
        ['Dec-15', 'Current', '36 months', ..., '',
         'https://www.lendingclub.com/brows

## working with string dataset

In [987]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

## Issue_d

In [988]:
header_strings[0] = 'Issue_date'
header_strings[0]

np.str_('Issue_date')

In [989]:
loan_data_strings[:,0] , np.unique(loan_data_strings[:,0]), np.unique(loan_data_strings[:,0]).size

(array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69'),
 array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
        'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69'),
 13)

In [990]:
#exclude "-15" from each rows
loan_data_strings[:,0] = np.char.strip(loan_data_strings[:,0],"-15")
loan_data_strings[:,0]

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], dtype='<U69')

In [991]:
#replacing month with respective number
months = np.array(['','Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
months


array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
      dtype='<U3')

In [992]:
for i in range(0, 13):
    loan_data_strings[:, 0] = np.where(np.isin(loan_data_strings[:, 0], months[i]),
                                       str(i),
                                       loan_data_strings[:, 0])
loan_data_strings[:,0] , np.unique(loan_data_strings[:,0])

(array(['5', '0', '9', ..., '6', '4', '12'], dtype='<U69'),
 array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69'))

## loan_status

In [993]:
np.unique(loan_data_strings[:,1]), np.unique(loan_data_strings[:,1]).size

(array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
        'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69'),
 9)

In [994]:
#catagorizing the values
status_bad = np.array(['','Charged Off','Default','Late (31-120 days)'])

In [995]:
loan_data_strings[:, 1] = np.where(np.isin(loan_data_strings[:, 1], status_bad), 0, 1)
np.unique(loan_data_strings[:,1])

array(['0', '1'], dtype='<U69')

In [996]:
header_strings

array(['Issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

## term

In [997]:
loan_data_strings[:,2] , np.unique(loan_data_strings[:,2])

(array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
       dtype='<U69'),
 array(['', '36 months', '60 months'], dtype='<U69'))

In [998]:
loan_data_strings[:,2] = np.char.strip(loan_data_strings[:,2]," months")
np.unique(loan_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [999]:
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',
                                  str(60),
                                  loan_data_strings[:,2])
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

In [1000]:
header_strings[3]

np.str_('grade')

## Grade and Subgrade

In [1001]:
loan_data_strings[:,3],loan_data_strings[:,4]

(array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69'),
 array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69'))

In [1002]:
np.unique(loan_data_strings[:,3]), 

(array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69'),)

In [1003]:
np.unique(loan_data_strings[:,4]).size ,np.unique(loan_data_strings[:,4])

(36,
 array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'))

In [1004]:
#filling the missing value-part 1
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,3] == i)& (loan_data_strings[:,4] == ''),
                                      i + '5',
                                      loan_data_strings[:,4])


In [1005]:
#filling the missing value- part 2
loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '',
                                      'H1',
                                      loan_data_strings[:,4])


In [1006]:
np.unique(loan_data_strings[:,4]).size , np.unique(loan_data_strings[:,4])

(36,
 array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'))

In [1007]:
#replacing string value of subgrade into numeric values (1 to 36)
keys = list(np.unique(loan_data_strings[:,4]))    
values = list(range(1,np.unique(loan_data_strings[:,4]).size+1))
dict_sub_grade = dict(zip(keys,values))

In [1008]:
dict_sub_grade

{np.str_('A1'): 1,
 np.str_('A2'): 2,
 np.str_('A3'): 3,
 np.str_('A4'): 4,
 np.str_('A5'): 5,
 np.str_('B1'): 6,
 np.str_('B2'): 7,
 np.str_('B3'): 8,
 np.str_('B4'): 9,
 np.str_('B5'): 10,
 np.str_('C1'): 11,
 np.str_('C2'): 12,
 np.str_('C3'): 13,
 np.str_('C4'): 14,
 np.str_('C5'): 15,
 np.str_('D1'): 16,
 np.str_('D2'): 17,
 np.str_('D3'): 18,
 np.str_('D4'): 19,
 np.str_('D5'): 20,
 np.str_('E1'): 21,
 np.str_('E2'): 22,
 np.str_('E3'): 23,
 np.str_('E4'): 24,
 np.str_('E5'): 25,
 np.str_('F1'): 26,
 np.str_('F2'): 27,
 np.str_('F3'): 28,
 np.str_('F4'): 29,
 np.str_('F5'): 30,
 np.str_('G1'): 31,
 np.str_('G2'): 32,
 np.str_('G3'): 33,
 np.str_('G4'): 34,
 np.str_('G5'): 35,
 np.str_('H1'): 36}

In [1009]:
for i in np.unique(loan_data_strings[:,4]):
    loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == i,
                                      str(dict_sub_grade[i]),
                                      loan_data_strings[:,4])

In [1010]:
np.unique(loan_data_strings[:,4]).size ,np.unique(loan_data_strings[:,4])

(36,
 array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
        '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
        '4', '5', '6', '7', '8', '9'], dtype='<U69'))

#### Removing grade column and its header
    sub grade contains the information that grade have.so it can be deleted

In [1011]:
loan_data_strings = np.delete(loan_data_strings, 3, axis = 1)
header_strings = np.delete(header_strings, 3)

In [1012]:
header_strings, 3, loan_data_strings[:,3]

(array(['Issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'url',
        'addr_state'], dtype='<U19'),
 3,
 array(['13', '5', '10', ..., '5', '17', '4'], dtype='<U69'))

## Verification_status

In [1013]:
loan_data_strings[:,4] , np.unique(loan_data_strings[:,4])

(array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
       dtype='<U69'),
 array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69'))

In [1014]:
loan_data_strings[:,4] = np.where((loan_data_strings[:,4]=='') | (loan_data_strings[:,4]=='Not Verified'),
                                  0,
                                  1)
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

## url

In [1015]:
loan_data_strings[:,5] = np.char.strip(loan_data_strings[:,5],'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [1016]:
#Check whether the ID column from loan_data_numeric and the URL column from loan_data_strings (after converting its data type to int) are equal using np.array_equal.
np.array_equal (loan_data_numeric[:,0],loan_data_strings[:,5].astype(int))

True

In [1017]:
loan_data_strings = np.delete(loan_data_strings,5,axis = 1)
header_strings= np.delete(header_strings,5,)

In [1018]:
loan_data_strings[:,5]
header_strings[5]

np.str_('addr_state')

In [1019]:
header_strings

array(['Issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
      dtype='<U19')

## 'addr_state'

In [1020]:
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [1021]:
np.unique(loan_data_strings[:,5]).size ,np.unique(loan_data_strings[:,5]) 

(50,
 array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'))

In [1022]:
states_names,states_counts = np.unique(loan_data_strings[:,5],return_counts=True)
states_counts_sorted = np.argsort(-states_counts)
states_names[states_counts_sorted],states_counts[states_counts_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'TN', 'CT', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DC', 'DE', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [1023]:
loan_data_strings[:,5] = np.where(loan_data_strings[:,5] == '',
                                  str(0),
                                  loan_data_strings[:,5])
np.unique(loan_data_strings[:,5])

array(['0', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [1024]:
#catagorize all of the states into 4
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [1025]:
#converting the string address into numeric value
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_west),str(1),loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_south),str(2),loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_midwest),str(3),loan_data_strings[:,5])
loan_data_strings[:,5] = np.where(np.isin(loan_data_strings[:,5],states_east),str(4),loan_data_strings[:,5])

In [1026]:
np.unique(loan_data_strings[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

In [1027]:
loan_data_strings

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [1028]:
#coverting the whole loan_data_strings dataset into numeric
loan_data_strings = loan_data_strings.astype(dtype = int)
loan_data_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [1029]:
#creating checkpoints
checkpoint_strings = checkpoint("checkpoint_strings",header_strings,loan_data_strings)


In [1030]:
checkpoint_strings['header'],checkpoint_strings['data']

(array(['Issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state'],
       dtype='<U19'),
 array([[ 5,  1, 36, 13,  1,  1],
        [ 0,  1, 36,  5,  1,  4],
        [ 9,  1, 36, 10,  1,  4],
        ...,
        [ 6,  1, 36,  5,  1,  1],
        [ 4,  1, 36, 17,  1,  3],
        [12,  1, 36,  4,  0,  3]]))

In [1031]:
np.array_equal(checkpoint_strings['data'], loan_data_strings)

True

# Working with Numeric Columns

In [1032]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [1033]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [1034]:
#checking is there any missing values
np.isnan(loan_data_numeric).sum()

np.int64(0)

In [1035]:
header_numeric[1] = "Loan_amount"
header_numeric

array(['id', 'Loan_amount', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [1036]:
#Checking whether the 'id' column initially had missing values and was later filled with temporary values while loading the dataset

np.isin(loan_data_numeric[:,0],temporary_fill).sum()

np.int64(0)

In [1037]:
#Checking whether each column column initially had missing values and was later filled with temporary values while loading the dataset
for i in range(0,loan_data_numeric.shape[1]):
    if np.isin(loan_data_numeric[:, i], temporary_fill).sum() > 0:
        print(np.isin(loan_data_numeric[:, i], temporary_fill).sum())


500
500
6004
501
500


In [1038]:
for i in range(0,loan_data_numeric.shape[1]):
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill,
                                      temporary_stats[0][column_numeric][i],
                                      loan_data_numeric[:,i])
                                      

In [1039]:
header_numeric

array(['id', 'Loan_amount', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## int_rate

In [1040]:
loan_data_numeric[:,3]  

array([13.33, 16.62, 16.62, ..., 16.62, 16.55, 16.62])

In [1041]:
loan_data_numeric[:,3] = loan_data_numeric[:,3]/100
loan_data_numeric[:,3]

array([0.13, 0.17, 0.17, ..., 0.17, 0.17, 0.17])

In [1042]:
header_numeric[3] = 'Interest_rate'
header_numeric[3]

np.str_('Interest_rate')

# Currency Exchange

In [1043]:
curency_file = 'F:/skillss/data analyst course/data processing via python udemy course/S28 - A Loan Data Example with NumPy/EUR-USD.csv'

In [1044]:
EUR_USD = np.genfromtxt(curency_file, 
                        delimiter=',',
                        skip_header=1,
                       usecols=3)
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [1045]:
exchange_rate = loan_data_strings[:,0]

for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1],
                             exchange_rate)

exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)
exchange_rate    

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [1046]:
exchange_rate = np.reshape(exchange_rate,(10000,1))
exchange_rate,exchange_rate.shape

(array([[1.1 ],
        [1.11],
        [1.13],
        ...,
        [1.12],
        [1.11],
        [1.09]]),
 (10000, 1))

In [1047]:
#adding the exchange_rate column with loan_data_numeric
loan_data_numeric = np.hstack((loan_data_numeric,exchange_rate))

In [1048]:
loan_data_numeric.shape, loan_data_numeric

((10000, 7),
 array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
        [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
        [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
        ...,
        [50415990.  ,    10000.  ,    10000.  , ...,      440.92,     2185.64,        1.12],
        [46154151.  ,    15273.46,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
        [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]]))

In [1049]:
#expand the header too.
header_numeric = np.hstack((header_numeric,"Exchange_rate"))
header_numeric

array(['id', 'Loan_amount', 'funded_amnt', 'Interest_rate', 'installment', 'total_pymnt',
       'Exchange_rate'], dtype='<U19')

## from usd to eur

In [1050]:
for i in [1,2,4,5]:
    loan_data_numeric = np.hstack((loan_data_numeric,np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6],(10000,1))))

In [1051]:
loan_data_numeric.shape

(10000, 11)

In [1052]:
#creating header name for the newly created columns
header_additional = []
for i in [1,2,4,5]:
    header_additional.append(np.array(header_numeric[i] + "_EUR"))

In [1053]:
header_additional

[array('Loan_amount_EUR', dtype='<U15'),
 array('funded_amnt_EUR', dtype='<U15'),
 array('installment_EUR', dtype='<U15'),
 array('total_pymnt_EUR', dtype='<U15')]

In [1054]:
#adding the column name with header_numeric
header_numeric = np.hstack((header_numeric,header_additional))
header_numeric

array(['id', 'Loan_amount', 'funded_amnt', 'Interest_rate', 'installment', 'total_pymnt',
       'Exchange_rate', 'Loan_amount_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [1055]:
#change the column name(adding "-USD" with the existing columns )
for i in [1,2,4,5]:
    header_numeric[i] = header_numeric[i] + '_USD'

In [1056]:
header_numeric

array(['id', 'Loan_amount_USD', 'funded_amnt_USD', 'Interest_rate', 'installment_USD',
       'total_pymnt_USD', 'Exchange_rate', 'Loan_amount_EUR', 'funded_amnt_EUR', 'installment_EUR',
       'total_pymnt_EUR'], dtype='<U19')

In [1057]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]
header_numeric = header_numeric[columns_index_order]
loan_data_numeric = loan_data_numeric[:,columns_index_order]

In [1058]:
header_numeric,loan_data_numeric

(array(['id', 'Loan_amount_USD', 'Loan_amount_EUR', 'funded_amnt_USD', 'funded_amnt_EUR',
        'Interest_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
        'Exchange_rate'], dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    15273.46,    13742.15, ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

In [1059]:
loan_data_numeric.shape,header_numeric.shape

((10000, 11), (11,))

# Checkpoint 2(Numeric)

In [1060]:
checkpoint_numeric = checkpoint('Checkpoint_Numeric',header_numeric,loan_data_numeric)

In [1061]:
checkpoint_numeric['header'],checkpoint_numeric['data']

(array(['id', 'Loan_amount_USD', 'Loan_amount_EUR', 'funded_amnt_USD', 'funded_amnt_EUR',
        'Interest_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR',
        'Exchange_rate'], dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    15273.46,    13742.15, ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

# Creating the whole dataset

In [1062]:
header_full = np.concatenate((checkpoint_strings['header'],checkpoint_numeric['header']))
header_full,header_full.size

(array(['Issue_date', 'loan_status', 'term', 'sub_grade', 'verification_status', 'addr_state', 'id',
        'Loan_amount_USD', 'Loan_amount_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'Interest_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'Exchange_rate'],
       dtype='<U19'),
 17)

In [1063]:
loan_data = np.hstack((checkpoint_strings['data'],checkpoint_numeric['data']))
loan_data.shape,loan_data

((10000, 17),
 array([[   5.  ,    1.  ,   36.  , ..., 9452.96, 8624.69,    1.1 ],
        [   0.  ,    1.  ,   36.  , ..., 4679.7 , 4232.39,    1.11],
        [   9.  ,    1.  ,   36.  , ..., 1969.83, 1750.04,    1.13],
        ...,
        [   6.  ,    1.  ,   36.  , ..., 2185.64, 1947.47,    1.12],
        [   4.  ,    1.  ,   36.  , ..., 3199.4 , 2878.63,    1.11],
        [  12.  ,    1.  ,   36.  , ...,  301.9 ,  276.11,    1.09]]))

In [1064]:
loan_data = loan_data[np.argsort(loan_data[:,0])]
loan_data

array([[   0.  ,    1.  ,   36.  , ..., 1047.52,  947.39,    1.11],
       [   0.  ,    1.  ,   36.  , ...,  738.9 ,  668.27,    1.11],
       [   0.  ,    1.  ,   36.  , ..., 1327.29, 1200.42,    1.11],
       ...,
       [  12.  ,    1.  ,   60.  , ...,  357.38,  326.85,    1.09],
       [  12.  ,    0.  ,   60.  , ...,    0.  ,    0.  ,    1.09],
       [  12.  ,    1.  ,   36.  , ...,  682.47,  624.17,    1.09]])

# storing the new dataset

In [1066]:
loan_data = np.vstack((header_full,loan_data))

In [1067]:
loan_data

array([['Issue_date', 'loan_status', 'term', ..., 'total_pymnt_USD', 'total_pymnt_EUR',
        'Exchange_rate'],
       ['0.0', '1.0', '36.0', ..., '1047.52', '947.393149723985', '1.1056866943836212'],
       ['0.0', '1.0', '36.0', ..., '738.9', '668.2724896241145', '1.1056866943836212'],
       ...,
       ['12.0', '1.0', '60.0', ..., '357.38', '326.8525909302222', '1.093398094177246'],
       ['12.0', '0.0', '60.0', ..., '0.0', '0.0', '1.093398094177246'],
       ['12.0', '1.0', '36.0', ..., '682.47', '624.1733945160579', '1.093398094177246']],
      dtype='<U32')

In [1068]:
fname

'F:/skillss/data analyst course/data processing via python udemy course/S28 - A Loan Data Example with NumPy/loan-data.csv'

In [1069]:
np.savetxt("F:/skillss/data analyst course/data processing via python udemy course/S28 - A Loan Data Example with NumPy/loan-data-preprocessed.csv", 
           loan_data, 
           fmt = '%s',
           delimiter = ',')